/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    kotlin("jvm") version "1.8.0"
    application
    id("dev.hydraulic.conveyor") version "1.4"
}

// You can get these values from the JCEF release notes in the corresponding GitHub Release.
val jcefVersion = "110.0.25"
val jcefCommitHash = "87476e9"
val cefVersion = "$jcefVersion+g75b1c96+chromium-110.0.5481.78"

dependencies {
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.0")
    implementation("me.friwi:jcefmaven:$jcefVersion")
}

group = "org.example"
version = "1.0"
description = "jcef-conveyor"

// Pipe our custom Gradle vars through to Conveyor.
tasks.named<hydraulic.conveyor.gradle.PrintConveyorConfigTask>("printConveyorConfig") {
    doLast {
        println("jcef.ver = $jcefVersion")
        println("jcef.commit-hash = $jcefCommitHash")
        println("jcef.cef-ver = \"$cefVersion\"")
    }
}

application {
    mainClass.set("jcefconveyor.SampleFrame")

    // JCEF needs access to some internal Java APIs.
    applicationDefaultJvmArgs = listOf(
        "--add-opens=java.desktop/java.awt.peer=ALL-UNNAMED",
        "--add-opens=java.desktop/sun.awt=ALL-UNNAMED",
        "--add-opens=java.desktop/sun.lwawt=ALL-UNNAMED",
        "--add-opens=java.desktop/sun.lwawt.macosx=ALL-UNNAMED",
    )
}

// Boilerplate.

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo1.maven.org/maven2/")
    }

    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
